package com.staricka.adventofcode2024.days

class Day6Test: DayTest(
    {Day6()},
    """
        ....#.....
        .........#
        ..........
        ..#.......
        .......#..
        ..........
        .#..^.....
        ........#.
        #.........
        ......#...
    """.trimIndent(),
    41,
    6
)